In [1]:
from eda_package.model import train_model
from eda_package import *

In [3]:
preprocessor = train_model()[1]

/home/alexbeecken/.pyenv/versions/noshowshield/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [5]:
    df = load_raw_data()
    df = clean_data(df)
    df = group_countries(df, COUNTRY_LIMIT)
    df = engineer_features(df)

    training_set, test_set = temporal_split(df, "2017-03-01")

    X_train, y_train = split_X_y(training_set)
    X_test, y_test = split_X_y(test_set)

In [6]:
feature_lists = get_feature_lists(X_train, ORDINAL_FEATURES_MAP)
preprocessor = create_preprocessor(feature_lists, ORDINAL_FEATURES_MAP)

X_train_processed = fit_transform_preprocessor(X_train, preprocessor)

In [7]:
sample_row = X_train.iloc[0]
sample_booking = pd.DataFrame([sample_row])
sample_booking

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,total_stay_nights,has_children,is_last_minute,season,total_previous_bookings,prev_cancel_ratio,total_revenue,segment_cancel_rate,has_deposit,arrival_date
0,Resort Hotel,342,2015,July,27,1,0,0,2,0.0,...,0,0,0,Summer,0,-1.0,0.0,0.147154,0,2015-07-01

In [8]:
dict = sample_row.to_dict()

# Convert Timestamp objects to strings for JSON serialization
for key, value in dict.items():
    if pd.api.types.is_datetime64_any_dtype(type(value)):
        dict[key] = str(value)

dict

{'hotel': 'Resort Hotel',
 'lead_time': 342,
 'arrival_date_year': 2015,
 'arrival_date_month': 'July',
 'arrival_date_week_number': 27,
 'arrival_date_day_of_month': 1,
 'stays_in_weekend_nights': 0,
 'stays_in_week_nights': 0,
 'adults': 2,
 'children': 0.0,
 'babies': 0,
 'meal': 'BB',
 'country': 'PRT',
 'market_segment': 'Direct',
 'distribution_channel': 'Direct',
 'is_repeated_guest': 0,
 'previous_cancellations': 0,
 'previous_bookings_not_canceled': 0,
 'reserved_room_type': 'C',
 'assigned_room_type': 'C',
 'booking_changes': 3,
 'deposit_type': 'No Deposit',
 'agent': 0.0,
 'company': 0.0,
 'days_in_waiting_list': 0,
 'customer_type': 'Transient',
 'adr': 0.0,
 'required_car_parking_spaces': 0,
 'total_of_special_requests': 0,
 'country_group': 'PRT',
 'total_stay_nights': 0,
 'has_children': 0,
 'is_last_minute': 0,
 'season': 'Summer',
 'total_previous_bookings': 0,
 'prev_cancel_ratio': -1.0,
 'total_revenue': 0.0,
 'segment_cancel_rate': 0.14715350728566587,
 'has_deposit': 0,
 'arrival_date': Timestamp('2015-07-01 00:00:00')}

In [9]:
#model.predict(sample_booking)

In [10]:
import requests

# Send your dict to the localhost API
response = requests.post(
    "http://localhost:8000/predict",
    json={"data": dict}
)

print("API Response:")
print(response.json())

TypeError: Object of type Timestamp is not JSON serializable

In [6]:
df = load_raw_data()

In [ ]:
model, preprocessor = train_model()

/home/alexbeecken/.pyenv/versions/noshowshield/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [7]:
training_set, test_set = temporal_split(df, "2017-03-01")

X_train, y_train = split_X_y(training_set)
X_test, y_test = split_X_y(test_set)

In [10]:
X_train_processed, X_test_processed = preprocess_pipeline(X_train, X_test)

In [11]:
X_train_processed

,num__lead_time,num__arrival_date_year,num__arrival_date_week_number,num__arrival_date_day_of_month,num__stays_in_weekend_nights,num__stays_in_week_nights,num__adults,num__children,num__babies,num__previous_cancellations,...,cat_onehot__assigned_room_type_P,cat_onehot__deposit_type_No Deposit,cat_onehot__deposit_type_Non Refund,cat_onehot__deposit_type_Refundable,cat_onehot__customer_type_Contract,cat_onehot__customer_type_Group,cat_onehot__customer_type_Transient,cat_onehot__customer_type_Transient-Party,cat_ordinal__arrival_date_month,cat_ordinal__meal
0,2.111940,-1.0,-0.208333,-1.000000,-0.5,-1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,2.0
1,5.059701,-1.0,-0.208333,-1.000000,-0.5,-1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,2.0
2,-0.388060,-1.0,-0.208333,-1.000000,-0.5,-0.5,-1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,2.0
3,-0.343284,-1.0,-0.208333,-1.000000,-0.5,-0.5,-1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,2.0
4,-0.335821,-1.0,-0.208333,-1.000000,-0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106962,-0.373134,1.0,-0.958333,0.666667,0.5,1.5,-1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
107001,0.149254,1.0,-0.958333,0.800000,0.0,1.5,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0
107008,-0.231343,1.0,-0.958333,0.733333,0.5,1.5,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,3.0
107026,-0.164179,1.0,-1.000000,0.400000,1.0,3.5,-2.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0
107072,-0.380597,1.0,-0.958333,0.733333,1.0,1.5,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0